name: test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Test
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn # 安装依赖
      - run: yarn test # 测试
